
title: My Resume
url: 'http://zhaorq.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Tianyi Zhao
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: zhaorq@gmail..com
phone: 917 513 2206
website: www.tianyi.zone #do not add http://
linkedin: zhaoty
github: zhaorq

# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
